FROM nginx:1.23.1-alpine as prod-stage
COPY /docker/nginx/conf.d/myblog.conf /etc/nginx/conf.d/myblog.conf
CMD ["nginx", "-g", "daemon off;"]

#to install vim to nginx server
RUN ["apk", "update"]
RUN ["apk", "add", "vim"]