FROM node:18-alpine3.15 as build
WORKDIR /app
#COPY package*.json ./
#RUN npm install
#COPY . .
#RUN npm run build
#dont forget to arrange host and port on package.json
#CMD ["npm", "run", "preview"] 